import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1789821128278 implements MigrationInterface {
    name = 'InitSchema1789821128278'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_email_lower" ON "users" (lower("email"))`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["marketplace","public","products","GENERATED_COLUMN","search_vector","\n      setweight(to_tsvector('simple', name), 'A') ||\n      setweight(to_tsvector('simple', description), 'B')\n    "]);
        await queryRunner.query(`CREATE TABLE "products" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "price" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "search_vector" tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('simple', name), 'A') ||
      setweight(to_tsvector('simple', description), 'B')
    ) STORED NOT NULL, "seller_id" bigint NOT NULL, CONSTRAINT "CHK_a5356b1aa4216c02c814622238" CHECK ("price" > 0), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_371cee1722905d974c4b50d1e5" ON "products" USING GIN ("search_vector") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "status" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" bigint NOT NULL, CONSTRAINT "CHK_1a57320d2e0e77b9fac6b0c0bc" CHECK ("status" IN ('completed', 'pending', 'cancelled')), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_pending" ON "orders" ("created_at") INCLUDE ("id", "user_id") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "idx_orders_user_created" ON "orders" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "qty" integer NOT NULL, "unit_price" integer NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL, CONSTRAINT "CHK_14b0c0285afef8e0ee0f7a284f" CHECK ("unit_price" > 0), CONSTRAINT "CHK_b92fec8668d71547482f1e5d2c" CHECK ("qty" > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_pending"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_371cee1722905d974c4b50d1e5"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","search_vector","marketplace","public","products"]);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."idx_users_email_lower"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
