import { MigrationInterface, QueryRunner } from "typeorm";

export class AddJobs1790116349422 implements MigrationInterface {
    name = 'AddJobs1790116349422'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "jobs" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "payload" text NOT NULL, "status" text NOT NULL DEFAULT 'new', "worker" text, "processed" integer NOT NULL DEFAULT '0', CONSTRAINT "CHK_7389941a629cf5899aee4f2f73" CHECK ("processed" >= 0), CONSTRAINT "CHK_f686108d5d714421bbec6182e4" CHECK ("status" IN ('new', 'done')), CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "jobs"`);
    }

}
